# Generated by Django 2.1.7 on 2019-02-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('projectuid', models.CharField(max_length=20)),
                ('featuredimage', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectuid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=20)),
                ('displaypicture', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('issutd', models.BooleanField()),
                ('graduationyear', models.IntegerField()),
                ('contactemail', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=300)),
                ('admingroup', models.ManyToManyField(to='projects.AdminGroup')),
                ('personallinks', models.ManyToManyField(to='projects.Links')),
                ('pillar', models.ManyToManyField(to='projects.Pillar')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ManyToManyField(to='projects.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ManyToManyField(to='projects.Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projects.Tag'),
        ),
    ]
