# Generated by Django 2.1.7 on 2019-02-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(default='', max_length=200)),
                ('project_uid', models.CharField(default='NONE_99999', max_length=20, primary_key=True, serialize=False)),
                ('featured_image', models.CharField(default='https://via.placeholder.com/150', max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('UROP', 'Undergraduate Research Opportunities Project'), ('UTOP', 'Undergraduate Teaching Opportunities Project'), ('ACAD', 'Academic Project (1D, 2D etc.)'), ('SELF', 'Student-initiated project'), ('NONE', "Unknown, or doesn't fall into any category")], default='NONE', max_length=4)),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACCEPT', 'Accepted Project, will display'), ('REJECT', 'Rejected Project, will not display'), ('PENDING', 'Pending Project, will not display')], default='PENDING', max_length=10)),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Tom', max_length=20)),
                ('display_picture', models.CharField(default='https://via.placeholder.com/150', max_length=200)),
                ('is_sutd', models.BooleanField(default='False')),
                ('graduation_year', models.IntegerField()),
                ('pillar', models.CharField(choices=[('FRSH', 'Freshmore'), ('EPD', 'Engineering Product and Design'), ('ESD', 'Engineering Systems Design'), ('ASD', 'Architecture and Sustainable Design'), ('ISTD', 'Information Systems Technology and Design'), ('PSTG', 'Post-graduate')], default='', max_length=4)),
                ('admin_groups', models.CharField(choices=[('UROP', 'Undergraduate Research Opportunities Project'), ('UTOP', 'Undergraduate Teaching Opportunities Project'), ('ACAD', 'Academic Project (1D, 2D etc.)'), ('SELF', 'Student-initiated project'), ('NONE', "Unknown, or doesn't fall into any category")], default='', max_length=4)),
                ('contact_email', models.CharField(default='none@example.com', max_length=200)),
                ('personal_links', models.CharField(default='', max_length=200)),
                ('bio', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projects.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='projects.User'),
        ),
    ]
