# Generated by Django 2.1.7 on 2019-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190228_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='displayname',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='graduationyear',
            new_name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectuid',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_uid',
            field=models.CharField(default='NONE_9999', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('UROP', 'Undergraduate Research Opportunities Project'), ('UTOP', 'Undergraduate Teaching Opportunities Project'), ('ACAD', 'Academic Project (1D, 2D etc.)'), ('SELF', 'Student-initiated project'), ('NONE', "Unknown, or doesn't fall into any category")], default='NONE', max_length=4),
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accepted Project, will display'), ('REJECT', 'Rejected Project, will not display'), ('PENDING', 'Pending Project, will not display')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='None', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_groups',
        ),
        migrations.AddField(
            model_name='user',
            name='admin_groups',
            field=models.CharField(choices=[('UROP', 'Undergraduate Research Opportunities Project'), ('UTOP', 'Undergraduate Teaching Opportunities Project'), ('ACAD', 'Academic Project (1D, 2D etc.)'), ('SELF', 'Student-initiated project'), ('NONE', "Unknown, or doesn't fall into any category")], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='isSUTD',
            field=models.BooleanField(default='False'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='pillar',
        ),
        migrations.AddField(
            model_name='user',
            name='pillar',
            field=models.CharField(choices=[('FRSH', 'Freshmore'), ('EPD', 'Engineering Product and Design'), ('ESD', 'Engineering Systems Design'), ('ASD', 'Architecture and Sustainable Design'), ('ISTD', 'Information Systems Technology and Design'), ('PSTG', 'Post-graduate')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Pillar',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
